### ISSUE TITLE
hex package

### ISSUE THREAD

**Issue by smokinguns** [arkgil/phx_load_gen#1]
Can't seem to find package in hex? Are you still working on this?

**Comment by arkgil** [comment]
Hi @smokinguns!

You may have been confused by the README, sorry, I didn't take my time to change it. The goal of this project was to generate load on the Phoenix channels for the demo of [Erlang Performance Lab](https://github.com/erlanglab/erlangpl). I had no intention to make it a generic load  testing tool for Phoenix channels or the Hex package.

I'm no longer working on this, but feel free to send some PRs or fork it if the need arises 🙂  I'll be more than happy to help if you have any questions 👍

**Comment by smokinguns** [comment]
I'm going to test it out. Closing the issue for now.
